[build-system]
requires = [
    "setuptools",
    "numpy>=2.0.0,<3.0.0; python_version < '3.9'",
    "numpy>=2.0.0,<3.0.0; python_version >= '3.9'",
    "cython>=0.25",
]
build-backend = "setuptools.build_meta"
